# Generated by Django 4.1.2 on 2022-11-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0002_alter_posts_user_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['posted'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('followed', models.CharField(editable=False, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('following', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Friends',
            },
        ),
    ]
