# Generated by Django 4.1.3 on 2022-11-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_posts_options_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name_plural': 'Followers'},
        ),
        migrations.AddField(
            model_name='likedpost',
            name='post_id',
            field=models.CharField(default='', editable=False, max_length=15),
        ),
    ]
