# Generated by Django 4.1.3 on 2022-11-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_friends_options_likedpost_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedpost',
            name='post_id',
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
