# Generated by Django 4.1.2 on 2022-11-03 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(max_length=7)),
                ('country', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=14)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='User-Dps/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Profile',
                'ordering': ['name'],
            },
        ),
    ]
